var hexagrams = [{
"111111": {"definition": "01. Force (乾 qián); The Creative; Possessing Creative Power & Skill",
            "hexagram": " ䷀ ",
            "number": "1",
            "description": "This tendency tends to lead to a negative attitude towards the People. If not, things get ugly. There is nothing wrong with being a Man. "},
  "000000": {"definition": "02. Field (坤 kūn); The Receptive; Needing Knowledge & Skill; Do not force matters and go with the flow",
            "hexagram": " ䷁ ",
            "number": "2",
            "description": "Avoid situations where your reasoning goes awry. There is an argument for avoiding situations where your reasoning goes awry."},
  "100010": {"definition": "03. Sprouting (屯 zhūn); Difficulty at the Beginning; Sprouting ",
            "hexagram": " ䷂ ",
            "number": "3",
            "description": "Teach yourself a lesson. Mash the bastard down in one long gulp, then credit your luck with the right combination of luck and luck. "},
  "010001": {"definition": "04. Enveloping (蒙 méng); Youthful Folly; Detained, Enveloped and Inexperienced",
            "hexagram": " ䷃ ",
            "number": "4",
            "description": " Knowledge is the key to survival. Knowledge is the only hope in this place. No matter which way you go, no matter which way you go. "},
  "111010": {"definition": "05. Attending (需 xū); Waiting; Uninvolvement (Wait for now), Nourishment ",
            "hexagram": " ䷄ ",
            "number": "5",
            "description": " The important thing was to cover this important territory before the hurricane hit. The first step was to cover the rest area, then the rest area. This was the last step. The problem here was to cover all the rest area in a manner that emphasized the importance of the Man."},
  "010111": {"definition": "06. Arguing (訟 sòng); Conflict; Engagement in Conflict ",
            "hexagram": " ䷅ ",
            "number": "6",
            "description": "Wander up to the bar with your hammer and seek out a drink. The bartender will recognize your concealed carry license and will recognize your concealed carry license. "},
  "010000": {"definition": "07. Leading (師 shī); The Army; Bringing Together, Teamwork ",
            "hexagram": " ䷆ ",
            "number": "7",
            "description": "Luck is key. Luck is an illusion. But in every case, the Luck Guy will score a huge stone and strike fear in every direction. "},
  "000010": {"definition": "08. Grouping (比 bǐ); Holding Together; Union ",
            "hexagram": " ䷇ ",
            "number": "8",
            "description": "The Church is a very complicated organization. The head of the church is usually the head of the church bureaucracy. There is a certain type of bureaucracy in the military."},
  "111011": {"definition": "09. Small Accumulating (小畜 xiǎo chù); Small Taming; Accumulating Resources",
            "hexagram": " ䷈ ",
            "number": "9",
            "description": "Humming. Yes... but in this case, I felt like Sodom. I’d forgotten all about Sodom before. I was a fool, for I was Sodom’s fault. And now I was Sodom’s fault. And now, I was Sodom’s fault. This time, I was Sodom’s fault. This is what the Bible says: “Whoever abides by law the Lord makes no man a man guilty; but he who makes a man guilty is a fugitive.” "},
  "110111": {"definition": "10. Treading (履 lǚ); Treading (Conduct); Continuing with Alertness",
            "hexagram": " ䷉ ",
            "number": "10",
            "description": "In the end, there is nothing in the world like a cure for the Fear. The Fear is the central nervous system of the human body. It is the central nervous system of the nervous system of the nervous system. The nervous system of the body. The central nervous system of the body. Freeze & Confinement."},
  "111000": {"definition": "11. Pervading (泰 tài); Peace; Pervading",
            "hexagram": " ䷊ ",
            "number": "11",
            "description": " Just passing through with it. A happy smile on the face of the great Landmark. “This is it,” said my attorney. “I’m your attorney.” He smiled distractedly. “OK, honey,” I said. "},
  "000111": {"definition": "12. Obstruction (否 pǐ); Standstill; Stagnation",
            "hexagram": " ䷋ ",
            "number": "12",
            "description": "However, once you reach the upper echelons of the higher order, you will need strong discipline, which will pay dividends in terms of academic freedom and the rule of law. "},
  "101111": {"definition": "13. Concording People (同人 tóng rén); Fellowship; Fellowship, Partnership",
            "hexagram": " ䷌ ",
            "number": "13",
            "description": "Learn not only from past mistakes but also from past misdeeds, but also from past misdeeds. Learn not only from past mistakes but also from past misdeeds. Learn not only from past mistakes but also from past misdeeds."},
  "111101": {"definition": "14. Great Possessing (大有 dà yǒu); Great Possession; Independence, Freedom",
            "hexagram": " ䷍ ",
            "number": "14",
            "description": "Because she is the Purest Woman on earth, she is a World-Class Woman. She is a World-Class Woman. This Purest Woman is the Third Door to the Kingdom Come Movement."},
  "001000": {"definition": "15. Humbling (謙 qiān); Modesty; Being Reserved, Refraining",
            "hexagram": " ䷎ ",
            "number": "15",
            "description": "And it breeds contempt for truth. Indeed. Here are a few tips and conss. 1. Don’t Try to Learn from Failure "},
  "000100": {"definition": "16. Providing-For (豫 yù); Enthusiasm; Inducement, New Stimulus",
            "hexagram": " ䷏ ",
            "number": "16",
            "description": "The Man in Black was born. He was a Christian. But he wasn’t a Christian. He was just a part of it. And it was important to him that Jesus lived according to His Word. Jesus lived according to His Word. He lived according to His Mission."},
  "100110": {"definition": "17. Following (隨 suí); Following; Following",
            "hexagram": " ䷐ ",
            "number": "17",
            "description": "Maybe this is the case. In the long run, you’ll want to drive at top speed and keep the wheels locked while you drift down the valley. Avoid that temptation and take a left on the freeway before you can make it to the next stoplight. "},
  "011001": {"definition": "18. Corrupting (蠱 gǔ); Work on the Decayed; Repairing",
            "hexagram": " ䷑ ",
            "number": "18",
            "description": "Wander the Treasure Island and catch the Treasure Island Run! To the right of this Great Western Front is the Great Western Front. In the name of the Army, it means the people who rule it. The people who rule it are those who rule it – not the military elite. The old guard, the new ones, are gone – but the new ones are gone. "},
  "110000": {"definition": "19. Nearing (臨 lín); Approach; Approaching Goal, Arriving ",
            "hexagram": " ䷒ ",
            "number": "19",
            "description": "Prepare accordingly. Remember that no matter what happens next, the path to victory lies in finding the balance between freedom and disaster. Be prepared for this. Be prepared. Never abandon yourself."},
  "000011": {"definition": "20. Viewing (觀 guān); Contemplation; The Withholding",
            "hexagram": " ䷓ ",
            "number": "20",
            "description": "Jesus, bless us all – but here comes the problem. I once lived in a neighborhood on the edge of Death Valley – on the edge of a fait-wash, in the twilight glow of the desert sun, when the rays of the wind came crashing down on me like a rocket."},
  "100101": {"definition": "21. Gnawing Bite (噬嗑 shì kè); Biting Through; Deciding",
            "hexagram": " ䷔ ",
            "number": "21",
            "description": "He is a religious figure in North America, a popular figure on the right and even considered one of the most dangerous mutants on the planet. "},
  "101001": {"definition": "22. Adorning (賁 bì); Grace; Embellishing",
            "hexagram": " ䷕ ",
            "number": "22",
            "description": "Avoid drama. Avoid drama. Avoid confusion. And that is the important thing in life. It is important to be a Man. And this is the only way to be Man. If everything else is going on in this world, well, stay focused... and if nothing else, well, keep going. No Man Can Save His Kingdom... Or Can He Save His Kingdom? "},
  "000001": {"definition": "23. Stripping (剝 bō); Splitting Apart; Stripping, Flaying",
            "hexagram": " ䷖ ",
            "number": "23",
            "description": "This is the style of sport that prevails in this land. Far too often in sports. The game is too complicated. The game is too complicated. The style of play is too complicated. We are wired into a society of individualism. The game is too complicated. "},
  "100000": {"definition": "24. Returning (復 fù); Return; Returning",
            "hexagram": " ䷗ ",
            "number": "24",
            "description": "Wonderful luck! Sage ruler – Time to Wander Last but not least, this time a very special time is coming up for you. This time is called the Lord’s Kingdom. "},
  "100111": {"definition": "25. Without Embroiling (無妄 wú wàng); Innocence; Without Rashness",
            "hexagram": " ䷘ ",
            "number": "25",
            "description": "It is simply a sporting convention, a mental illusion, a delusion, or whatever it means to be a professional. It is simply not fit for the sport. It is simply not fit for the sport. History is a very heavy thing, even in a world of Top-Down Slopes. The sport has always seemed a bit like the distant future of organized sport in the blink of an eye. "},
  "111001": {"definition": "26. Great Accumulating (大畜 dà chù); Great Taming; Accumulating Wisdom",
            "hexagram": " ䷙ ",
            "number": "26",
            "description": "This is the story of Leary. It is the central tension of our time. He is our hero, but also a hindrance on both him and us. And we must come to terms with that tension, at the core of our culture. "},
  "100001": {"definition": "27. Swallowing (頤 yí); Mouth Corners; Seeking Nourishment",
            "hexagram": " ䷚ ",
            "number": "27",
            "description": " Make sure the water quality is right for you. Some people argue that “authority “despicable homicide.” But some experts agree. "},
  "011110": {"definition": "28. Great Exceeding (大過 dà guò); Great Preponderance; Great Surpassing",
            "hexagram": " ䷛ ",
            "number": "28",
            "description": "The margin of margin in this work appears to be in the hands of a man with a nasty temper. The margin of the margin in this work appears to be in the hands of a man with a nasty temper."},
  "010010": {"definition": "29. Gorge (坎 kǎn); The Abysmal Water; Darkness, Gorge",
            "hexagram": " ䷜ ",
            "number": "29",
            "description": "The Man Knows... How to Be A Man... "},
  "101101": {"definition": "30. Radiance (離 lí); The Clinging; Clinging, Attachment",
            "hexagram": " ䷝ ",
            "number": "30",
            "description": "Calm Down... and Seek Refuge... in Peace and Understanding "},
  "001110": {"definition": "31. Conjoining (咸 xián); Influence; Attraction",
            "hexagram": " ䷞ ",
            "number": "31",
            "description": "The first lesson in this series is the most important lesson in my life. I have been wanting to do this for years."},
  "011100": {"definition": "32. Persevering (恆 héng); Duration; Perseverance",
            "hexagram": " ䷟ ",
            "number": "32",
            "description": "But the Thundering Woman is incapable of recognizing or caring for any of her surroundings. This slobbering will not get through to being a Woman. She will reject authority and violence – which are the hallmarks of a dangerous and underappreciated culture. "},
  "001111": {"definition": "33. Retiring (遯 dùn); Retreat; Withdrawing",
            "hexagram": " ䷠ ",
            "number": "33",
            "description": " In the face of overwhelming evidence that every cell in the world is wired to work on, the essential difference is to work on something that matters: What matters is the essential thing in life – not just the magazine."},
  "111100": {"definition": "34. Great Invigorating (大壯 dà zhuàng); Great Power; Great Boldness",
            "hexagram": " ䷡ ",
            "number": "34",
            "description": "This is especially true in Thunder: because the only hope of survival is to “care” and “work” – even if that means risking serious physical and mental harm. This is the key to survival – in spite of all that bad blood, and because we can all be Evil. But even if we can’t care, we can’t possibly be a Good People."},
  "000101": {"definition": "35. Prospering (晉 jìn); Progress; Expansion, Promotion",
            "hexagram": " ䷢ ",
            "number": "35",
            "description": "“This man with the right instincts is going to need your help to turn this corner.” He smiled distractedly. “The only people who make a living doing it are the people who make it.” "},
  "101000": {"definition": "36. Brightness Hiding (明夷 míng yí); Darkening of the Light; Brilliance Injured",
            "hexagram": " ䷣ ",
            "number": "36",
            "description": " Paranoid Terror... and the Vile of the Paranoid... A Terrible Experience with the... ... Flight... or Flight? Or is it worse, subconsciously speaking?"},
  "101011": {"definition": "37. Dwelling People (家人 jiā rén); The Family; Family",
            "hexagram": " ䷤ ",
            "number": "37",
            "description": "Hummingbird: Husband in a Husband’s Life : Hummingbird: Husband in a Couple’s Life "},
  "110101": {"definition": "38. Polarising (睽 kuí); Opposition; Division, Divergence",
            "hexagram": " ䷥ ",
            "number": "38",
            "description": "The geek culture has changed massively in the last two decades, and we must be doing everything in our power to keep it that way. "},
  "001010": {"definition": "39. Limping (蹇 jiǎn); Obstruction; Halting, Hardship",
            "hexagram": " ䷦ ",
            "number": "39",
            "description": "But not here. This is not the way to live. No longer is it. No longer is it. And no longer is it. No longer is it. And no longer is it. And no longer is it. The Life of A Savage Savage is on. We’re here, ladies and gentlemen."},
  "010100": {"definition": "40. Taking-Apart (解 xiè); Deliverance; Liberation, Solution",
            "hexagram": " ䷧ ",
            "number": "40",
            "description": "A Gun Club, or perhaps your friend’s Club, which you may or may not be attending – for a period of at least two weeks – to the point that you are unable to spend any more than twenty-four hours in any state of need, except at the discretion of the general public. "},
  "110001": {"definition": "41. Diminishing (損 sǔn); Decrease; Decrease",
            "hexagram": " ䷨ ",
            "number": "41",
            "description": "It is imperative to establish a high standard of living, that our culture of consumption is pure and simple. We are exposed to the cruel side of things – especially those of the upper and upper strata. "},
  "100011": {"definition": "42. Augmenting (益 yì); Increase; Increase",
            "hexagram": " ䷩ ",
            "number": "42",
            "description": "This is the path I’ve come to in the Psychoanalytic Asylum. The only hope now, after years of avoiding trouble, is to carve up some decent head and work it into some kind of permanent formula for self-preservation. "},
  "111110": {"definition": "43. Parting (夬 guài); Breakthrough; Separation",
            "hexagram": " ䷪ ",
            "number": "43",
            "description": "You will come to a place where you are entitled to higher office than in any town on earth. Stand up for what you believe. Stand up for what you believe. Stand up for what you believe."},
  "011111": {"definition": "44. Coupling (姤 gòu); Coming to Meet; Encountering",
            "hexagram": " ䷫ ",
            "number": "44",
            "description": "Zephyr is a demonic creature, half-innocent; a savage creature of some kind. She is an assistant professor of history at the University of Southern California. She is the author of two books, The Savage Savage Shadow, and one of the funniest collections of Savage Woman advice sheets. "},
  "000110": {"definition": "45. Clustering (萃 cuì); Gathering Together; Association, Companionship",
            "hexagram": " ䷬ ",
            "number": "45",
            "description": "The Man at the Top. This is the kind of person who makes a fool of himself. He makes a mockery of himself. But what makes a fool of himself is his style. He is a man of wealth, not of morals. He is a writer. And so do I. "},
  "011000": {"definition": "46. Ascending (升 shēng); Pushing Upward; Growing Upward",
            "hexagram": " ䷭ ",
            "number": "46",
            "description": "What is Superiority? Asterile reasoning is a complex concept, like any other skill- you learn. There are many hallmarks of a genius: It comes down to a sense of almost total elitism."},
  "010110": {"definition": "47. Confining (困 kùn); Oppression; Exhaustion",
            "hexagram": " ䷮ ",
            "number": "47",
            "description": "But in spite of this, the widow of this evil highway freak will not hesitate to cut the cord on any given trip – even if that means cutting her income or even even driving her place as a hotel check. And she knows she has a fantastic story to tell."},
  "011010": {"definition": "48. Welling (井 jǐng); The Well; Replenishing, Renewal",
            "hexagram": " ䷯ ",
            "number": "48",
            "description": "I saw this in the refugee camp. It was a strange place to be a part of, but I sensed the connection between these two realities. The idea of becoming a refugee came to pass from the vibes of the Youth Movement, which I considered indispensable in the struggle for national self-preservation in the name of the survival of the fittest. "},
  "101110": {"definition": "49. Skinning (革 gé); Revolution; Abolishing the Old",
            "hexagram": " ䷰ ",
            "number": "49",
            "description": "Meanwhile, the primitive Church remains oblivious to the hazards of Man-made Sodomy. All signs are being sought, in every form, for Truth. Jesus will be resurrected from the dead in the Kingdom of the Gomorrah. No Man can possibly understand the depths of this madness. "},
  "011101": {"definition": "50. Holding (鼎 dǐng); The Cauldron; Establishing the New",
            "hexagram": " ䷱ ",
            "number": "50",
            "description": "Play it safe: on the go you will need an internet connection to your computer, and on the go you will need an in-depth article describing how to use JavaScript in your work. "},
  "100100": {"definition": "51. Shake (震 zhèn); Arousing; Mobilizing",
            "hexagram": " ䷲ ",
            "number": "51",
            "description": "Shout out to the Thunder people for the Thunder Thunder: Yes, we can’t forget these poor bastards. They don’t deserve that honor. "},
  "001001": {"definition": "52. Bound (艮 gèn); The Keeping Still; Immobility",
            "hexagram": " ䷳ ",
            "number": "52",
            "description": "Far too often our culture is hijacked by these instincts."},
  "001011": {"definition": "53. Infiltrating (漸 jiàn); Development; Auspicious Outlook, Infiltration",
            "hexagram": " ䷴ ",
            "number": "53",
            "description": "But once you get there, things get complicated. "},
  "110100": {"definition": "54. Converting The Maiden (歸妹 guī mèi); The Marrying Maiden; Marrying",
            "hexagram": " ䷵ ",
            "number": "54",
            "description": " No footing. No water. No rhythm. No sun. "},
  "101100": {"definition": "55. Abounding (豐 fēng); Abundance; Goal Reached, Ambition Achieved",
            "hexagram": " ䷶ ",
            "number": "55",
            "description": "And no matter how bad the odds are, this is going to be no different. The Lightning will not abandon the old guard. It will reject the late bloomer. It will reject the cactus-sucker. It will reject the cactus-sucker. "},
  "001101": {"definition": "56. Sojourning (旅 lǚ); The Wanderer; Travel",
            "hexagram": " ䷷ ",
            "number": "56",
            "description": " was slumped in the passenger seat of the car. A thousand miles an hour of pure stinking air and dust, fueled only by the cactus, is the purest energy we’ve ever had. "},
  "011011": {"definition": "57. Ground (巽 xùn); The Gentle; Subtle Influence",
            "hexagram": " ䷸ ",
            "number": "57",
            "description": "Teach yourself. Teach yourself. Volunteer. Volunteer is a very heavy thing to do. Volunteer is like entering your own pharmacy. Volunteer is like entering a Royal Swedish Hospital. "},
  "110110": {"definition": "58. Open (兌 duì); The Joyous; Overt Influence",
            "hexagram": " ䷹ ",
            "number": "58",
            "description": "But in spite of all that, there is still hope in this incredibly valuable and occasionally painful truth: If you stay true to the faith and the cause, then you can always have a fine, healthy heart."},
  "010011": {"definition": "59. Dispersing (渙 huàn); Dispersion; Dispersal",
            "hexagram": " ䷺ ",
            "number": "59",
            "description": "The Sixth Doctor was standing around watching the prisoners. “What’s happening?” he asked. “Just treat the wounded like goddamn lepers.” "},
  "110010": {"definition": "60. Articulating (節 jié); Limitation; Discipline",
            "hexagram": " ䷻ ",
            "number": "60",
            "description": "In spite of these virtues, we tend to shy away from trouble and trouble. But when we approach trouble, we tend to notice that we can’t never quite grasped the essential tension of being a Man."},
  "110011": {"definition": "61. Centre Confirming (中孚 zhōng fú); Inner Truth; Staying Focused,Avoid Misrepresentation",
            "hexagram": " ䷼ ",
            "number": "61",
            "description": "The man behind the TV set said the “Do Not Disturb” sign was actually a man in the yellow shirt of a cop. "},
  "001100": {"definition": "62. Small Exceeding (小過 xiǎo guò); Small Preponderance; Small Surpassing",
            "hexagram": " ䷽ ",
            "number": "62",
            "description": "Be a Man, Be an Eagle or Nothing..."},
  "101010": {"definition": "63. Already_Fording (既濟 jì jì); After Completion; Completion",
            "hexagram": " ䷾ ",
            "number": "63",
            "description": "Most people don’t know the psychology of water."},
  "010101": {"definition": "64. Not-Yet Fording (未濟 wèi jì); Before Completion; Incompletion",
            "hexagram": " ䷿ ",
            "number": "64",
            "description": "Manhood... and the Terrible Implications of Extremely Dangerous Drug Use."}
}]
